---
title: "DataCleaning_Collegescorecard"
author: "Sara"
date: "October 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(dplyr)
```

```{r, echo =FALSE}
merged_master <- read.csv(here::here("dataset", "MERGED2015_16_PP.csv"),stringsAsFactors = FALSE)
earnings_master <- read.csv(here::here("dataset", "Treasury Elements.csv"),stringsAsFactors = FALSE)
```

#converting character type col into a numeric
```{r, echo =FALSE}
merged_master$SAT_AVG <- as.numeric(merged_master$SAT_AVG)
merged_master$AVGFACSAL <- as.numeric(merged_master$AVGFACSAL)

merged_master$GRAD_DEBT_MDN_SUPP <- as.numeric(merged_master$GRAD_DEBT_MDN_SUPP) 
earnings_master$MD_EARN_WNE_P10 <- as.numeric(earnings_master$MD_EARN_WNE_P10)

merged_master$AVGFACSAL <- as.numeric(merged_master$AVGFACSAL)
merged_master$TUITIONFEE_IN <- as.numeric(merged_master$TUITIONFEE_IN)
merged_master$ADM_RATE <- as.numeric(merged_master$ADM_RATE)
```

#converting columns with categorical variables into factors
```{r, echo =FALSE}

merged_master$STABBR <- as.factor(merged_master$STABBR)
merged_master$CONTROL <- as.factor(merged_master$CONTROL)

merged_master$PREDDEG <- as.factor(merged_master$PREDDEG)
merged_master$HIGHDEG <- as.factor(merged_master$HIGHDEG)


merged_master$INSTNM <- as.factor(merged_master$INSTNM)
merged_master$CCBASIC <- as.factor(merged_master$CCBASIC)
merged_master$REGION <- as.factor(merged_master$REGION)

```

#converting CONTROL levels to descriptors instead of numbers
```{r, echo =FALSE}

levels(merged_master$CONTROL) <-revalue(levels(merged_master$CONTROL), 
                     c("1"="Public", "2"="Private nonprofit", "3"="Private for-profit"))


levels(merged_master$REGION) <-revalue(levels(merged_master$REGION), 
                                        c("0"= "U.S. Service Schools",
                                          "1"= "New England (CT, ME, MA, NH, RI, VT)",
                                          "2" ="Mid East (DE, DC, MD, NJ, NY, PA)",
                                          "3"= "Great Lakes (IL, IN, MI, OH, WI)",
                                          "4" ="Plains (IA, KS, MN, MO, NE, ND, SD)",
                                          "5"= "Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV)",
                                          "6"= "Southwest (AZ, NM, OK, TX)",
                                          "7"= "Rocky Mountains (CO, ID, MT, UT, WY)",
                                          "8" ="Far West (AK, CA, HI, NV, OR, WA)",
                                          "9" ="Outlying Areas (AS, FM, GU, MH, MP, PR, PW, VI)"))

levels(merged_master$HIGHDEG) <-revalue(levels(merged_master$HIGHDEG), 
                                     c("0"="Non-degree-granting",
                                       "1"="Certificate degree", 
                                       "2"="Associate degree", 
                                       "3"="Bachelor's degree", 
                                       "4"="Graduate Degree"))


levels(merged_master$CCBASIC) <-revalue(levels(merged_master$CCBASIC), 
                                       c("14"="Baccalaureate/Associate's Colleges: Associate's Dominant", 
                                         "15"="Doctoral Universities: Highest Research Activity", 
                                         "16"="Doctoral Universities: Highest Research Activity",
                                         "17"="Doctoral Universities: Moderate Research Activity", 
                                         "18"="Master's Colleges & Universities: Larger Programs", 
                                         "19"="Master's Colleges & Universities: Medium Programs",
                                         "20"="Master's Colleges & Universities: Small Programs", 
                                         "21"="Baccalaureate Colleges: Arts & Sciences Focus", 
                                         "22"="Baccalaureate Colleges: Diverse Fields",
                                         "23"="Baccalaureate/Associate's Colleges: Mixed Baccalaureate/Associate's", 
                                         "24"="Special Focus Four-Year: Faith-Related Institutions", 
                                         "25"="Special Focus Four-Year: Medical Schools & Centers",
                                         "26"="Special Focus Four-Year: Other Health Professions Schools", 
                                         "27"="Special Focus Four-Year: Engineering Schools", 
                                         "28"="Special Focus Four-Year: Other Technology-Related Schools",
                                         "29"="Special Focus Four-Year: Business & Management Schools", 
                                         "30"="Special Focus Four-Year: Arts, Music & Design Schools", 
                                         "31"="Special Focus Four-Year: Law Schools",
                                         "32"="Special Focus Four-Year: Other Special Focus Institutions"))

ccbasic <- c("Baccalaureate/Associate's Colleges: Associate's Dominant", 
              "Doctoral Universities: Highest Research Activity", 
              "Doctoral Universities: Highest Research Activity",
              "Doctoral Universities: Moderate Research Activity", 
              "Master's Colleges & Universities: Larger Programs", 
              "Master's Colleges & Universities: Medium Programs",
              "Master's Colleges & Universities: Small Programs", 
              "Baccalaureate Colleges: Arts & Sciences Focus", 
              "Baccalaureate Colleges: Diverse Fields",
              "Baccalaureate/Associate's Colleges: Mixed Baccalaureate/Associate's", 
              "Special Focus Four-Year: Faith-Related Institutions", 
              "Special Focus Four-Year: Medical Schools & Centers",
              "Special Focus Four-Year: Other Health Professions Schools", 
              "Special Focus Four-Year: Engineering Schools", 
              "Special Focus Four-Year: Other Technology-Related Schools",
              "Special Focus Four-Year: Business & Management Schools", 
              "Special Focus Four-Year: Arts, Music & Design Schools", 
              "Special Focus Four-Year: Law Schools",
              "Special Focus Four-Year: Other Special Focus Institutions")


```


```{r, echo =FALSE}
merged_master <- plyr::rename(merged_master, c("ï..UNITID" = "UNITID"))
earnings_master <- plyr::rename(earnings_master, c("ï..UNITID" = "UNITID"))
basicdata <- merged_master %>% 
              dplyr::select(UNITID, OPEID,OPEID6,INSTNM, CITY,STABBR, REGION, LATITUDE, LONGITUDE,
                      MAIN, PREDDEG, HIGHDEG, CONTROL, CCBASIC,  
                      ADM_RATE, SAT_AVG, UGDS, PCTPELL, TUITIONFEE_IN, AVGFACSAL,
#Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion)
                      C100_4,
#Total share of enrollment of undergraduate degree-seeking students whose race is-
                      UGDS_WHITE,	UGDS_BLACK,	UGDS_HISP,	UGDS_ASIAN,	
#Percent of students whose parents' highest educational level is middle/high school, post secondary ed
                     PAR_ED_PCT_MS,PAR_ED_PCT_HS,PAR_ED_PCT_PS,
                     FEMALE_DEBT_MDN, MALE_DEBT_MDN,
                     GRAD_DEBT_MDN_SUPP)

earnings <- earnings_master %>% 
              dplyr::select(UNITID,MD_EARN_WNE_P10)
```


```{r, echo =FALSE}

#ALLDATA has data: BASIC +PCI52 + DEBT +EARNINGS - WITH NA VALUES
alldata <- inner_join(basicdata,earnings, by="UNITID")
write.csv(x = alldata, file = "alldata.csv")

#ALLDATA1 has data: BASIC +PCI52 + DEBT +EARNINGS - WITHOUT NA VALUES
alldata1 <- alldata[complete.cases(alldata),]
write.csv(x = alldata, file = "noNAdata.csv")
```
